# Generated by Django 3.0.7 on 2020-06-05 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 23, 23, 0, 307624), verbose_name='date published'),
        ),
    ]
